import { useState } from "react";

export default function RentasData() {
    const [rentaArr, setRentas] = useState([{
        "idRentar": 1,
        "idUsuario": 1,
        "idPelicula": 1,
        "fecha_rentar": "2023-12-22",
        "dias_de_renta": 10,
        "estatus": 1
    }, {
        "idRentar": 2,
        "idUsuario": 2,
        "idPelicula": 2,
        "fecha_rentar": "2023-10-31",
        "dias_de_renta": 15,
        "estatus": 1
    }, {
        "idRentar": 3,
        "idUsuario": 3,
        "idPelicula": 3,
        "fecha_rentar": "2024-01-31",
        "dias_de_renta": 66,
        "estatus": 0
    }, {
        "idRentar": 4,
        "idUsuario": 4,
        "idPelicula": 4,
        "fecha_rentar": "2023-05-12",
        "dias_de_renta": 40,
        "estatus": 1
    }, {
        "idRentar": 5,
        "idUsuario": 5,
        "idPelicula": 5,
        "fecha_rentar": "2023-12-15",
        "dias_de_renta": 95,
        "estatus": 0
    }, {
        "idRentar": 6,
        "idUsuario": 6,
        "idPelicula": 6,
        "fecha_rentar": "2023-04-08",
        "dias_de_renta": 40,
        "estatus": 0
    }, {
        "idRentar": 7,
        "idUsuario": 7,
        "idPelicula": 7,
        "fecha_rentar": "2023-09-07",
        "dias_de_renta": 79,
        "estatus": 0
    }, {
        "idRentar": 8,
        "idUsuario": 8,
        "idPelicula": 8,
        "fecha_rentar": "2023-05-14",
        "dias_de_renta": 76,
        "estatus": 0
    }, {
        "idRentar": 9,
        "idUsuario": 9,
        "idPelicula": 9,
        "fecha_rentar": "2023-04-29",
        "dias_de_renta": 81,
        "estatus": 0
    }, {
        "idRentar": 10,
        "idUsuario": 10,
        "idPelicula": 10,
        "fecha_rentar": "2023-10-09",
        "dias_de_renta": 87,
        "estatus": 1
    }, {
        "idRentar": 11,
        "idUsuario": 11,
        "idPelicula": 11,
        "fecha_rentar": "2023-12-29",
        "dias_de_renta": 18,
        "estatus": 1
    }, {
        "idRentar": 12,
        "idUsuario": 12,
        "idPelicula": 12,
        "fecha_rentar": "2023-07-02",
        "dias_de_renta": 86,
        "estatus": 1
    }, {
        "idRentar": 13,
        "idUsuario": 13,
        "idPelicula": 13,
        "fecha_rentar": "2023-09-21",
        "dias_de_renta": 14,
        "estatus": 1
    }, {
        "idRentar": 14,
        "idUsuario": 14,
        "idPelicula": 14,
        "fecha_rentar": "2023-10-31",
        "dias_de_renta": 75,
        "estatus": 0
    }, {
        "idRentar": 15,
        "idUsuario": 15,
        "idPelicula": 15,
        "fecha_rentar": "2023-07-30",
        "dias_de_renta": 91,
        "estatus": 0
    }]);

    return { rentaArr, setRentas };

}